// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArd7Ic6-f7o7PRRGAXlAyqUrcWMmXeJWo',
    appId: '1:146425350356:web:755cdce9a104219b9f1341',
    messagingSenderId: '146425350356',
    projectId: 'trabalho-progmobile',
    authDomain: 'trabalho-progmobile.firebaseapp.com',
    databaseURL: 'https://trabalho-progmobile-default-rtdb.firebaseio.com',
    storageBucket: 'trabalho-progmobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEu-f9GWFOt6lk-7mKf_7hFUplrdJSU6E',
    appId: '1:146425350356:android:27a0a6d2a85d53909f1341',
    messagingSenderId: '146425350356',
    projectId: 'trabalho-progmobile',
    databaseURL: 'https://trabalho-progmobile-default-rtdb.firebaseio.com',
    storageBucket: 'trabalho-progmobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJqIgzJ_h7AR-O_iEeW3XcWm2zMUEaz6Q',
    appId: '1:146425350356:ios:d10bc6e5f628ec609f1341',
    messagingSenderId: '146425350356',
    projectId: 'trabalho-progmobile',
    databaseURL: 'https://trabalho-progmobile-default-rtdb.firebaseio.com',
    storageBucket: 'trabalho-progmobile.firebasestorage.app',
    iosBundleId: 'com.example.trabalho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJqIgzJ_h7AR-O_iEeW3XcWm2zMUEaz6Q',
    appId: '1:146425350356:ios:d10bc6e5f628ec609f1341',
    messagingSenderId: '146425350356',
    projectId: 'trabalho-progmobile',
    databaseURL: 'https://trabalho-progmobile-default-rtdb.firebaseio.com',
    storageBucket: 'trabalho-progmobile.firebasestorage.app',
    iosBundleId: 'com.example.trabalho',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArd7Ic6-f7o7PRRGAXlAyqUrcWMmXeJWo',
    appId: '1:146425350356:web:f15a275d22b001449f1341',
    messagingSenderId: '146425350356',
    projectId: 'trabalho-progmobile',
    authDomain: 'trabalho-progmobile.firebaseapp.com',
    databaseURL: 'https://trabalho-progmobile-default-rtdb.firebaseio.com',
    storageBucket: 'trabalho-progmobile.firebasestorage.app',
  );

}